import type { QuizQuestion } from './types'

// 문제 은행 — 통합사회 1학기 3~4단원. 세션마다 셔플해 10문제 출제.
export const QUIZ_BANK: QuizQuestion[] = [
  // ── 기후 ─────────────────────────────────────
  {
    id: 'c1',
    category: 'climate',
    question: '연중 고온다습하고 매일 오후 스콜(소나기)이 내리며 계절 변화가 거의 없는 기후는?',
    choices: ['열대우림 기후', '사바나 기후', '지중해성 기후', '툰드라 기후'],
    answerIndex: 0,
    explanation: '연중 고온다우에 스콜이 내리면 열대우림 기후(Af)입니다.',
  },
  {
    id: 'c2',
    category: 'climate',
    question: '우기와 건기가 뚜렷하게 나뉘고 키 큰 풀밭에 나무가 드문드문 자라는 초원 기후는?',
    choices: ['열대우림 기후', '사바나 기후', '스텝 기후', '냉대 습윤 기후'],
    answerIndex: 1,
    explanation: '연중 고온 + 우기/건기 구분 + 초원 = 사바나 기후. 세렝게티가 대표적입니다.',
  },
  {
    id: 'c3',
    category: 'climate',
    question: '여름은 덥고 건조하며 겨울은 온화하고 비가 내려, 올리브·포도 재배가 발달한 기후는?',
    choices: ['온난 습윤 기후', '서안 해양성 기후', '지중해성 기후', '온대 겨울 건조 기후'],
    answerIndex: 2,
    explanation: '여름 건조·겨울 강수가 최대 특징인 지중해성 기후(Cs)입니다.',
  },
  {
    id: 'c4',
    category: 'climate',
    question: '편서풍과 난류의 영향으로 연교차가 작고 연중 강수가 고르며 낙농업이 발달한 기후는?',
    choices: ['서안 해양성 기후', '지중해성 기후', '냉대 습윤 기후', '사막 기후'],
    answerIndex: 0,
    explanation: '편서풍 + 난류로 위도에 비해 온화한 서안 해양성 기후(Cfb)입니다. 서유럽이 대표적입니다.',
  },
  {
    id: 'c5',
    category: 'climate',
    question: '가장 따뜻한 달도 0℃ 미만이라 일 년 내내 눈과 얼음으로 덮여 있는 기후는?',
    choices: ['툰드라 기후', '빙설 기후', '냉대 겨울 건조 기후', '고산 기후'],
    answerIndex: 1,
    explanation: '최난월도 0℃ 미만이면 빙설 기후(EF). 남극·그린란드 내륙이 해당합니다. (툰드라는 0~10℃)',
  },
  {
    id: 'c6',
    category: 'climate',
    question: '적도 부근이지만 해발 고도가 높아 일 년 내내 봄처럼 서늘한 기후로, 잉카 문명이 발달한 곳은?',
    choices: ['사바나 기후', '열대우림 기후', '고산 기후', '지중해성 기후'],
    answerIndex: 2,
    explanation: '적도 부근 고지대의 상춘 기후 = 고산 기후. 안데스의 키토·쿠스코가 대표적입니다.',
  },
  {
    id: 'c7',
    category: 'climate',
    question: '몽골·중앙아시아에 나타나며, 사막 주변에 짧은 풀이 자라 유목이 발달한 기후는?',
    choices: ['사막 기후', '스텝 기후', '사바나 기후', '툰드라 기후'],
    answerIndex: 1,
    explanation: '사막보다 비가 조금 더 와 초원이 형성되는 스텝 기후(BS). 유목·게르가 키워드입니다.',
  },
  {
    id: 'c8',
    category: 'climate',
    question: '온대 기후 중 여름 강수가 집중되고 겨울이 건조하며 벼농사·차 재배가 발달한 기후는?',
    choices: ['온난 습윤 기후', '온대 겨울 건조 기후', '서안 해양성 기후', '지중해성 기후'],
    answerIndex: 1,
    explanation: '겨울 강수가 확 줄어드는 온대 겨울 건조 기후(Cw). 중국 남부가 대표적입니다.',
  },
  {
    id: 'c9',
    category: 'climate',
    question: '이누이트가 순록을 기르고, 짧은 여름에만 이끼가 자라며 땅속은 늘 얼어 있는(영구 동토) 기후는?',
    choices: ['냉대 습윤 기후', '툰드라 기후', '빙설 기후', '스텝 기후'],
    answerIndex: 1,
    explanation: '최난월 0~10℃로 이끼·풀이 자라는 툰드라 기후(ET)입니다.',
  },
  {
    id: 'c10',
    category: 'climate',
    question: '침엽수림(타이가)이 넓게 분포하고 겨울이 길고 추우며 임업이 발달한 기후는?',
    choices: ['냉대 습윤 기후', '툰드라 기후', '온난 습윤 기후', '사바나 기후'],
    answerIndex: 0,
    explanation: '긴 겨울과 타이가가 특징인 냉대 습윤 기후(Df). 러시아·캐나다에 넓게 분포합니다.',
  },
  {
    id: 'c11',
    category: 'climate',
    question: '기온 그래프가 남반구처럼 1월이 가장 높고 7월이 가장 낮게 나타나는 나라는?',
    choices: ['대한민국', '오스트레일리아', '일본', '독일'],
    answerIndex: 1,
    explanation: '남반구는 계절이 북반구와 반대라 1월이 여름입니다. 오스트레일리아가 남반구입니다.',
  },

  // ── 환경문제 ─────────────────────────────────
  {
    id: 'e1',
    category: 'environment',
    question: '황산화물·질소산화물이 대기 중에서 물과 반응해 삼림과 석조 문화재를 훼손하는 문제는?',
    choices: ['산성비', '오존층 파괴', '사막화', '미세 플라스틱'],
    answerIndex: 0,
    explanation: '황산화물·질소산화물 → pH 5.6 미만의 산성비. 삼림 고사와 대리석 부식이 특징입니다.',
  },
  {
    id: 'e2',
    category: 'environment',
    question: '프레온가스(CFC)가 원인이며 남극 상공에 구멍(오존홀)이 생기는 환경문제는?',
    choices: ['산성비', '오존층 파괴', '열대림 파괴', '해양 오염'],
    answerIndex: 1,
    explanation: '프레온가스가 성층권 오존층을 파괴합니다. 남극 오존홀·자외선 증가가 키워드입니다.',
  },
  {
    id: 'e3',
    category: 'environment',
    question: '과도한 방목·경작과 가뭄으로 사헬 지대의 초원이 메마른 땅으로 변하는 문제는?',
    choices: ['열대림 파괴', '사막화', '산성비', '미세 먼지'],
    answerIndex: 1,
    explanation: '사헬 지대의 토지 황폐화 = 사막화. 사막화 방지 협약(UNCCD)과 연결됩니다.',
  },
  {
    id: 'e4',
    category: 'environment',
    question: '"지구의 허파"가 목재·농경지·팜유 개발로 사라져 생물 다양성이 감소하는 문제는?',
    choices: ['사막화', '열대림 파괴', '오존층 파괴', '산성비'],
    answerIndex: 1,
    explanation: '아마존·콩고 분지 등 열대 우림 파괴. 탄소 흡수 감소와 생물 다양성 감소가 문제입니다.',
  },
  {
    id: 'e5',
    category: 'environment',
    question: '지름 5mm 이하의 작은 플라스틱이 먹이 사슬을 따라 사람의 식탁까지 올라오는 문제는?',
    choices: ['해양 오염', '미세 플라스틱', '미세 먼지', '산성비'],
    answerIndex: 1,
    explanation: '5mm 이하 미세 플라스틱은 물고기가 삼켜 먹이 사슬을 통해 사람에게 되돌아옵니다.',
  },
  {
    id: 'e6',
    category: 'environment',
    question: '다음 중 국경을 넘어 이동하기 때문에 주변국 간 협력이 특히 중요한 문제로 묶인 것은?',
    choices: [
      '산성비·미세 먼지',
      '미세 플라스틱·오존층 파괴',
      '열대림 파괴·사막화',
      '해양 오염·빙하 융해',
    ],
    answerIndex: 0,
    explanation: '산성비와 미세 먼지는 바람(편서풍)을 타고 국경을 넘어 이웃 나라에 피해를 줍니다.',
  },

  // ── 국제협약 ─────────────────────────────────
  {
    id: 't1',
    category: 'treaty',
    question: '오존층을 파괴하는 프레온가스(CFC) 사용을 규제하기 위한 국제 협약은?',
    choices: ['람사르 협약', '몬트리올 의정서', '바젤 협약', '파리 협정'],
    answerIndex: 1,
    explanation: '오존층 = 몬트리올 의정서(1987). 국제 사회가 성공적으로 대응한 대표 사례입니다.',
  },
  {
    id: 't2',
    category: 'treaty',
    question: '물새 서식지로 중요한 습지를 보호하기 위한 협약으로, 우리나라 순천만이 등록된 것은?',
    choices: ['람사르 협약', '런던 협약', '바젤 협약', '생물 다양성 협약'],
    answerIndex: 0,
    explanation: '습지 보호 = 람사르 협약(1971). 순천만·우포늪이 등록되어 있습니다.',
  },
  {
    id: 't3',
    category: 'treaty',
    question: '유해 폐기물이 국경을 넘어 개발도상국으로 옮겨져 처리되는 것을 규제하는 협약은?',
    choices: ['런던 협약', '바젤 협약', '몬트리올 의정서', '교토 의정서'],
    answerIndex: 1,
    explanation: '유해 폐기물의 국가 간 이동 규제 = 바젤 협약(1989). 런던 협약(해양 투기)과 구분하세요.',
  },
  {
    id: 't4',
    category: 'treaty',
    question: '선진국에 온실가스 감축 의무를 처음으로 부과한 의정서는?',
    choices: ['파리 협정', '교토 의정서', '기후 변화 협약', '몬트리올 의정서'],
    answerIndex: 1,
    explanation: '교토 의정서(1997)는 주로 선진국에 감축 의무를 부과했습니다. 파리 협정(모든 국가)과 구분하세요.',
  },
  {
    id: 't5',
    category: 'treaty',
    question: '선진국과 개발도상국을 포함한 모든 당사국이 온실가스 감축에 참여하기로 한 신기후체제는?',
    choices: ['교토 의정서', '파리 협정', '기후 변화 협약', '바젤 협약'],
    answerIndex: 1,
    explanation: '파리 협정(2015)은 모든 당사국이 자발적 감축 목표(NDC)로 참여합니다. 1.5~2℃ 억제가 목표입니다.',
  },
  {
    id: 't6',
    category: 'treaty',
    question: '폐기물을 바다에 버리는 해양 투기로 인한 해양 오염을 막기 위한 협약은?',
    choices: ['런던 협약', '바젤 협약', '람사르 협약', '사막화 방지 협약'],
    answerIndex: 0,
    explanation: '폐기물 해양 투기 규제 = 런던 협약(1972). "바다에 버리는 것"이 키워드입니다.',
  },
  {
    id: 't7',
    category: 'treaty',
    question: '"기후 변화 협약 → ( ) → 파리 협정"의 흐름에서 괄호에 들어갈 협약은?',
    choices: ['람사르 협약', '교토 의정서', '바젤 협약', '생물 다양성 협약'],
    answerIndex: 1,
    explanation: '기후변화협약(1992) → 교토 의정서(1997) → 파리 협정(2015) 순서입니다.',
  },
  {
    id: 't8',
    category: 'treaty',
    question: '생물종 감소를 막고 생물 자원을 지속 가능하게 이용하기 위해 리우 회의에서 채택된 협약은?',
    choices: ['생물 다양성 협약', '사막화 방지 협약', '람사르 협약', '몬트리올 의정서'],
    answerIndex: 0,
    explanation: '생물종·유전자원 보호 = 생물 다양성 협약(1992). 리우 회의에서 채택되었습니다.',
  },

  // ── 문화 ─────────────────────────────────────
  {
    id: 'u1',
    category: 'culture',
    question: '열대 기후 지역에서 습기와 해충을 피하려고 지면에서 띄워 짓는 전통 가옥은?',
    choices: ['이글루', '고상 가옥', '게르', '흙벽돌집'],
    answerIndex: 1,
    explanation: '열대의 고온다습에 대응해 바닥을 띄운 고상 가옥으로 통풍과 습기·해충을 막습니다.',
  },
  {
    id: 'u2',
    category: 'culture',
    question: '건조 기후 지역에서 강한 햇빛과 모래바람을 막기 위한 전통 의복의 특징은?',
    choices: [
      '온몸을 감싸는 헐렁한 옷',
      '동물 가죽으로 만든 두꺼운 옷',
      '얇고 짧은 옷',
      '털가죽 부츠와 파카',
    ],
    answerIndex: 0,
    explanation: '건조 지역은 햇빛·모래바람·수분 증발을 막으려 온몸을 감싸는 헐렁한 옷을 입습니다.',
  },
  {
    id: 'u3',
    category: 'culture',
    question: '몽골 유목민이 이동 생활에 편리하도록 사용하는 조립식 이동 가옥은?',
    choices: ['게르', '이글루', '고상 가옥', '통나무집'],
    answerIndex: 0,
    explanation: '스텝 기후의 유목 생활에 맞는 조립식 이동 가옥이 게르입니다.',
  },
  {
    id: 'u4',
    category: 'culture',
    question: '스웨덴에서 일 년 중 낮이 가장 긴 날을 기념하며 즐기는, 백야와 관련된 축제는?',
    choices: ['홀리 축제', '하지 축제(미드소마르)', '송끄란 축제', '리우 카니발'],
    answerIndex: 1,
    explanation: '고위도의 백야와 관련된 하지 축제(미드소마르)입니다.',
  },
  {
    id: 'u5',
    category: 'culture',
    question: '브라질에서 삼바 리듬에 맞춰 열리며, 가톨릭 사순절 직전에 즐기던 데서 유래한 축제는?',
    choices: ['리우 카니발', '태양제', '부뇰 토마토 축제', '홀리 축제'],
    answerIndex: 0,
    explanation: '리우 카니발은 유럽 가톨릭 문화와 아프리카 문화가 융합된 라틴 아메리카의 축제입니다.',
  },
  {
    id: 'u6',
    category: 'culture',
    question: '타이에서 전통 설날에 서로 물을 뿌리며 축복하는, 더위를 식히는 의미도 있는 축제는?',
    choices: ['홀리 축제', '송끄란 축제', '태양제', '하지 축제'],
    answerIndex: 1,
    explanation: '타이의 물 축제 송끄란입니다. 가장 더운 시기(4월)에 열립니다.',
  },
  {
    id: 'u7',
    category: 'culture',
    question: '이슬람교의 생활 문화와 거리가 먼 것은?',
    choices: ['돼지고기를 먹지 않는다', '라마단 기간에 금식한다', '소를 신성시한다', '하루 다섯 번 기도한다'],
    answerIndex: 2,
    explanation: '소를 신성시하는 것은 힌두교입니다. 이슬람교는 돼지고기 금기·라마단·기도가 특징입니다.',
  },
  {
    id: 'u8',
    category: 'culture',
    question: '인도에서 봄맞이로 서로에게 색색의 가루를 뿌리며 즐기는 힌두교 축제는?',
    choices: ['홀리 축제', '송끄란 축제', '리우 카니발', '태양제'],
    answerIndex: 0,
    explanation: '인도의 "색의 축제" 홀리입니다. 봄과 풍요를 기원하는 힌두교 축제입니다.',
  },

  // ── 지도 찾기 (map-click) ────────────────────
  {
    id: 'm1',
    category: 'map',
    question: '지도에서 사바나 기후가 대표적인 나라를 클릭하세요. (예: 동아프리카)',
    answerIsos: ['KE', 'TZ', 'NG'],
    explanation: '케냐·탄자니아는 사바나 기후의 대표 지역으로, 세렝게티 초원과 야생동물로 유명합니다.',
  },
  {
    id: 'm2',
    category: 'map',
    question: '지도에서 사막 기후가 국토 대부분을 차지하는 나라를 클릭하세요. (예: 아라비아반도)',
    answerIsos: ['SA', 'EG', 'DZ', 'LY'],
    explanation: '사우디아라비아·이집트·알제리는 사막 기후(BW)가 대부분입니다.',
  },
  {
    id: 'm3',
    category: 'map',
    question: '지도에서 냉대 기후가 넓게 나타나는 나라를 클릭하세요. (예: 북반구 고위도 대국)',
    answerIsos: ['RU', 'CA', 'FI', 'SE'],
    explanation: '러시아·캐나다는 냉대 기후와 타이가(침엽수림)가 넓게 분포합니다.',
  },
  {
    id: 'm4',
    category: 'map',
    question: '지도에서 지중해성 기후가 나타나는 나라를 클릭하세요. (예: 지중해 연안)',
    answerIsos: ['ES', 'IT', 'GR', 'TR'],
    explanation: '에스파냐·이탈리아·그리스는 지중해성 기후로 올리브·포도 재배가 발달했습니다.',
  },
  {
    id: 'm5',
    category: 'map',
    question: '지도에서 열대 우림(아마존)이 분포하는 나라를 클릭하세요.',
    answerIsos: ['BR', 'CO', 'PE'],
    explanation: '브라질은 아마존 열대 우림이 분포하며, 열대림 파괴 문제와 관련이 깊습니다.',
  },
]
